## Authorizations
# Uncomment out the merging for each environment that you'd like to include.
# You can also just copy and paste the tree (do not include the "authorizations") to each
# environment if you need something different per enviornment.
authorizations: &AUTHORIZATIONS
  group_base: ou=groups,dc=test,dc=com
  ## Requires config.ldap_check_group_membership in devise.rb be true
  # Can have multiple values, must match all to be authorized
  required_groups:
    # If only a group name is given, membership will be checked against "uniqueMember"
    - cn=admins,ou=groups,dc=test,dc=com
    - cn=users,ou=groups,dc=test,dc=com
    # If an array is given, the first element will be the attribute to check against, the second the group name
    - ["moreMembers", "cn=users,ou=groups,dc=test,dc=com"]
  ## Requires config.ldap_check_attributes in devise.rb to be true
  ## Can have multiple attributes and values, must match all to be authorized
  require_attribute:
    objectClass: inetOrgPerson
    authorizationRole: postsAdmin

## Environment

development:
  host: ldap06.pfadipatria.com
  port: 389
  attribute: mail
  base: dc=pfadipatria,dc=com
  admin_user: cn=admin,dc=pfadipatria,dc=com
  admin_password: txcu1cBeSPKGSaAS
  ssl: false
  # <<: *AUTHORIZATIONS

test:
  host: localhost
  port: 3389
  attribute: cn
  base: ou=people,dc=test,dc=com
  admin_user: cn=admin,dc=test,dc=com
  admin_password: admin_password
  ssl: simple_tls
  # <<: *AUTHORIZATIONS

production:
  host: <%= ENV['RAILS_LDAP_HOST'] || 'ldap06.mrr.pfadipatria.com' %>
  port: <%= ENV['RAILS_LDAP_PORT'] || '389' %>
  attribute: <%= ENV['RAILS_LDAP_ATTRIBUTE'] || 'mail' %>
  base: <%= ENV['RAILS_LDAP_BASE'] || 'dc=pfadipatria,dc=com' %>
  admin_user: <%= ENV['RAILS_LDAP_ADMIN_USER'] || 'cn=admin,dc=pfadipatria,dc=com' %>
  admin_password: <%= ENV['RAILS_LDAP_ADMIN_PASSWORD'] || 'txcu1cBeSPKGSaAS' %>
  ssl: <%= ENV['RAILS_LDAP_SSL'] || false %>
  # <<: *AUTHORIZATIONS
